## spring security 配置
security:
  oauth2:
    client:
      client-id: ENC(tz2NM4GcmnE7sNJTYL8ZSg==)
      client-secret: ENC(tz2NM4GcmnE7sNJTYL8ZSg==)
      scope: server
## 定时任务
# 数据源
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ${MYSQL-USER:root}
      password: ${MYSQL-PWD:root}
      url: jdbc:mysql://${MYSQL-HOST:pigx-mysql}:${MYSQL-PORT:3306}/${MYSQL-DB:pigxx_job}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true
  elasticjob:
    # 分布式任务协调依赖zookeeper
    zookeeper:
      server-lists: ${ZOOKEEPER-HOST:pigx-zookeeper}:${ZOOKEEPER-PORT:2181}
      namespace: pigx-daemon
    # 普通任务
    simples:
      spring-simple-job:
        job-class: com.pig4cloud.pigx.daemon.elastic.job.PigxSimpleJob
        cron: 0 0 0/1 * * ?
        sharding-total-count: 3
        sharding-item-parameters: 0=service1,1=service2,2=service3
        eventTraceRdbDataSource: 'dataSource'
        listener:
          listener-class: com.pig4cloud.pigx.daemon.elastic.listener.PigxElasticJobListener
      spring-simple-job2:
        job-class: com.pig4cloud.pigx.daemon.elastic.job.PigxSimpleJob2
        cron: 0 0 0/1 * * ?
        sharding-total-count: 3
        sharding-item-parameters: 0=service1,1=service2,2=service3
        eventTraceRdbDataSource: 'dataSource'
        listener:
          listener-class: com.pig4cloud.pigx.daemon.elastic.listener.PigxElasticJobListener
    # 简单任务
    dataflows:
      spring-dataflow-job:
        job-class: com.pig4cloud.pigx.daemon.elastic.job.PigxDataflowJob
        cron: 0 0 0/1 * * ?
        sharding-total-count: 3
        sharding-item-parameters: 0=service1,1=service2,2=service3
        streaming-process: true
        eventTraceRdbDataSource: 'dataSource'
        listener:
          distributed-listener-class: com.pig4cloud.pigx.daemon.elastic.listener.PigxDistributeElasticJobListener
          started-timeout-milliseconds: 5000
          completed-timeout-milliseconds: 10000